# Preprocessing Data
## Data Cleaning (Missing value & Outlier)

### Employee payroll data for Cook County employees
#### Source: www.data.gov

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import mode
from scipy import stats

In [2]:
EP = pd.read_csv("D:/DATA MINING/EP.csv",sep=";")
EP.head()

Fiscal Period First Name Middle Init                Bureau  \
0        2016Q1      LANCE         NaN               Sheriff   
1        2016Q1    DEBORAH           L  Clerk of Circuit Ct.   
2        2016Q1      BRIAN         NaN               Sheriff   
3        2016Q1    MICHAEL           H               Sheriff   
4        2016Q1      KEVIN           T               Sheriff   

                      Office Name     Job              Job Title  Base Pay  \
0       DEPARTMENT OF CORRECTIONS  1239.0     Deputy Sheriff D2B  16649.94   
1  CLERK OF CRCT CRT OFF. OF CLER  1335.0         Court Clerk II  14045.69   
2               POLICE DEPARTMENT  1231.0  County Police Officer  20066.89   
3       DEPARTMENT OF CORRECTIONS  1239.0   Correctional Officer  16867.12   
4       DEPARTMENT OF CORRECTIONS  1239.0   Correctional Officer  11953.60   

   Employee Identifier Original Hire Date  
0            9505782.0         10/13/1998  
1            9516186.0         12/07/1981  
2            9505244.0         03/01/1989  
3            9508862.0         07/01/1991  
4             700324.0         06/15/2015

In [3]:
#statistika deskriptif

EP.describe()

Job      Base Pay  Employee Identifier
count  3056.000000   3074.000000         2.918000e+03
mean   2378.669830  14995.055264         7.651281e+06
std    1665.653727   9127.483003         3.578267e+06
min    1007.000000      0.000000         5.370000e+02
25%    1239.000000  10834.562500         9.501586e+06
50%    1300.000000  14424.190000         9.508922e+06
75%    4891.000000  17556.302500         9.517469e+06
max    4898.000000  88846.200000         9.935075e+06

In [4]:
#missing value

np.sum(EP.isnull())

Fiscal Period             0
First Name                0
Middle Init            1224
Bureau                  124
Office Name              23
Job                      23
Job Title                15
Base Pay                  5
Employee Identifier     161
Original Hire Date        0
dtype: int64

In [5]:
#imputasi dengan mean

EP['Job'] = EP['Job'].fillna(EP['Job'].mean())
EP['Base Pay'] = EP['Base Pay'].fillna(EP['Base Pay'].mean())
EP['Employee Identifier'] = EP['Employee Identifier'].fillna(EP['Employee Identifier'].mean())
np.sum(EP.isnull())

Fiscal Period             0
First Name                0
Middle Init            1224
Bureau                  124
Office Name              23
Job                       0
Job Title                15
Base Pay                  0
Employee Identifier       0
Original Hire Date        0
dtype: int64

In [6]:
#modus

print([EP['Middle Init'].mode()],
      [EP['Bureau'].mode()],
      [EP['Office Name'].mode()],
      [EP['Job Title'].mode()])

[0    A
dtype: object] [0    Bureau of Health
dtype: object] [0    DEPARTMENT OF CORRECTIONS
dtype: object] [0    Correctional Officer
dtype: object]


In [7]:
#imputasi ddengan modus 

EP['Middle Init']=EP['Middle Init'].fillna(EP['Middle Init']).dropna().mode()[0]
EP['Bureau']=EP['Bureau'].fillna(EP['Bureau']).dropna().mode()[0]
EP['Office Name']=EP['Office Name'].fillna(EP['Office Name']).dropna().mode()[0]
EP['Job Title']=EP['Job Title'].fillna(EP['Job Title']).dropna().mode()[0]
np.sum(EP.isnull())

Fiscal Period          0
First Name             0
Middle Init            0
Bureau                 0
Office Name            0
Job                    0
Job Title              0
Base Pay               0
Employee Identifier    0
Original Hire Date     0
dtype: int64

In [8]:
#mengatasi outlier

EP1=EP.drop(['Fiscal Period','First Name','Middle Init','Bureau','Office Name','Job Title','Original Hire Date'],1)
z = np.abs(stats.zscore(EP1._get_numeric_data()))
print(z)
EP=EP[(z<3).all(axis=1)]
print(EP.shape)

[[0.68690008 0.18148481 0.53246486]
 [0.62903911 0.10411322 0.53545206]
 [0.69172183 0.5562085  0.53231039]
 ...
 [0.68027018 0.07510324 1.76604891]
 [0.80081388 0.43190419 0.53116793]
 [0.70437892 0.31987805 0.53157076]]
(3018, 10)


In [9]:
EP.head()

Fiscal Period First Name Middle Init            Bureau  \
0        2016Q1      LANCE           A  Bureau of Health   
1        2016Q1    DEBORAH           A  Bureau of Health   
2        2016Q1      BRIAN           A  Bureau of Health   
3        2016Q1    MICHAEL           A  Bureau of Health   
4        2016Q1      KEVIN           A  Bureau of Health   

                 Office Name     Job             Job Title  Base Pay  \
0  DEPARTMENT OF CORRECTIONS  1239.0  Correctional Officer  16649.94   
1  DEPARTMENT OF CORRECTIONS  1335.0  Correctional Officer  14045.69   
2  DEPARTMENT OF CORRECTIONS  1231.0  Correctional Officer  20066.89   
3  DEPARTMENT OF CORRECTIONS  1239.0  Correctional Officer  16867.12   
4  DEPARTMENT OF CORRECTIONS  1239.0  Correctional Officer  11953.60   

   Employee Identifier Original Hire Date  
0            9505782.0         10/13/1998  
1            9516186.0         12/07/1981  
2            9505244.0         03/01/1989  
3            9508862.0         07/01/1991  
4             700324.0         06/15/2015